// src/modules/auth/dto/register.dto.ts

import { IsString, IsEmail, IsNotEmpty, IsDateString, IsPhoneNumber } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class RegisterDto {
  @ApiProperty({ example: 'John', description: 'User\'s first name' })
  @IsString()
  @IsNotEmpty()
  readonly firstName!: string;

  @ApiProperty({ example: 'Smith', description: 'User\'s middle name, if they have one' })
  @IsString()
  readonly middleName!: string;

  @ApiProperty({ example: 'Doe', description: 'User\'s last name' })
  @IsString()
  @IsNotEmpty()
  readonly lastName!: string;

  @ApiProperty({ example: '1990-01-01', description: 'User\'s date of birth (ISO 8601 format: YYYY-MM-DD)' })
  @IsDateString()
  readonly dateOfBirth!: string; // Will be converted to Date object

  @ApiProperty({ example: '+250788123456', description: 'User\'s date of birth (ISO 8601 format: YYYY-MM-DD)' })
  @IsPhoneNumber()
  readonly phoneNumber!: string; 
  
  @ApiProperty({ example: 'test@customer.com', description: 'The email address of the user.' })
  @IsEmail()
  @IsNotEmpty()
  readonly email!: string;

  @ApiProperty({ example: 'P@ssword123', description: 'The user\'s password (min 8 chars).' })
  @IsString()
  @IsNotEmpty()
  readonly password!: string;
  
  // Note: accountNumber, role, balance, and creditScore are now generated by AuthService
}